import Vue from 'vue';
import {
  Tabs,
  Table,
  Button,
  Input,
  Select,
  TabPane,
  Form,
  FormItem,
  Dropdown,
  Dialog,
  DropdownItem,
  DropdownMenu,
  Menu,
  Scrollbar,
  Submenu,
  MenuItem,
  Option,
  TableColumn,
  Pagination,
  loading,
  Autocomplete,
  DatePicker,
  Checkbox,
  Col,
  Row,
  InputNumber,
  Tag,
  Slider,
  Transfer,
  Badge,
  Tree,
  Card,
  Upload,
} from 'element-ui';

Vue.use(Upload);
Vue.use(Card);
Vue.use(Tree);
Vue.use(Badge);
Vue.use(Tabs);
Vue.use(Table);
Vue.use(Input);
Vue.use(Button);
Vue.use(Select);
Vue.use(TabPane);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Dropdown);
Vue.use(Dialog);
Vue.use(DropdownItem);
Vue.use(DropdownMenu);
Vue.use(Menu);
Vue.use(Scrollbar);
Vue.use(Submenu);
Vue.use(MenuItem);
Vue.use(Option);
Vue.use(TableColumn);
Vue.use(Pagination);
Vue.use(loading);
Vue.use(Autocomplete);
Vue.use(DatePicker);
Vue.use(Checkbox);
Vue.use(Row);
Vue.use(Col);
Vue.use(InputNumber);
Vue.use(Tag);
Vue.use(Slider);
Vue.use(Transfer);
